config/routes.rb
Rails.application.routes.draw do
  resources :scrapers do
    resources :rulesets, except: [:index] do
      get 'scrape', to: 'rulesets#scrape', as: 'single_scrape'
    end
  end

  resources :scrape_results, only: %i(show edit update destroy)

  root 'scrapers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ruleset.rb
class Ruleset < ApplicationRecord
  belongs_to :scraper
  has_many :scrape_results, dependent: :destroy

  validates_presence_of :name, :url, :parent_rule, :parent_rule_is_xpath
  validates_inclusion_of :parent_rule_is_xpath, in: [true, false]

  def has_child_rule?
    self.child_rule.present?
  end
end

app/models/scrape_result.rb
class ScrapeResult < ApplicationRecord
  belongs_to :ruleset
  delegate :name, :description, to: :ruleset
end

app/models/scraper.rb
class Scraper < ApplicationRecord
  has_many :rulesets, dependent: :destroy

  validates_presence_of :name

  scope :by_id, -> { order(:id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger, :warning, :info
end

app/controllers/rulesets_controller.rb
class RulesetsController < ApplicationController
  before_action :fetch_scraper
  before_action :fetch_ruleset, only: %i[edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_ruleset

  def new
    @ruleset = @scraper.rulesets.build
  end

  def create
    @ruleset = @scraper.rulesets.build(ruleset_params)
    if @ruleset.save
      flash[:success] = "Ruleset #{@ruleset.name} created successfully!"
      redirect_to scraper_ruleset_path(@scraper, @ruleset)
    else
      flash.now[:danger] = @ruleset.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @ruleset = Ruleset.includes(:scrape_results).find(params[:id])
  end

  def edit; end

  def update
    if @ruleset.update(ruleset_params)
      flash[:success] = "Ruleset #{@ruleset.name} updated successfully!"
      redirect_to scraper_ruleset_path(@scraper, @ruleset)
    else
      flash.now[:danger] = @ruleset.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @ruleset.destroy
    flash[:success] = 'Ruleset deleted successfully'
    redirect_to scraper_path(params[:scraper_id])
  end

  def scrape
    ruleset = Ruleset.find(params[:ruleset_id])
    result = HandleSingleItemScrapingService.new(ruleset).call
    flash[result.keys.first] = result.values.first
    redirect_to scraper_ruleset_path(ruleset.scraper, ruleset)
  end

  private

  def fetch_scraper
    @scraper = Scraper.find(params[:scraper_id])
  end

  def fetch_ruleset
    @ruleset = @scraper.rulesets.find(params[:id])
  end

  def invalid_ruleset
    redirect_to scraper_path(params[:scraper_id]), info: 'Invalid ID'
  end

  def ruleset_params
    params.require(:ruleset).permit(:name, :description, :url, :parent_rule, :child_rule,
      :parent_rule_is_xpath, :child_rule_is_xpath)
  end
end

app/controllers/scrape_results_controller.rb
class ScrapeResultsController < ApplicationController
  before_action :fetch_scrape_result
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_scrape_result

  def show; end

  def edit; end

  def update
    if @scrape_result.update(scrape_result_params.merge(manual_change: true))
      flash[:success] = "Scrape result '#{@scrape_result.name}' updated successfully!"
      redirect_to scrape_result_path(@scrape_result)
    else
      flash.now[:danger] = @scrape_result.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @scrape_result.destroy
    flash[:success] = 'Scrape Result deleted successfully'
    redirect_to scraper_ruleset_path(@scrape_result.ruleset.scraper, @scrape_result.ruleset)
  end

  private

  def fetch_scrape_result
    @scrape_result = ScrapeResult.includes(ruleset: :scraper).find(params[:id])
  end

  def scrape_result_params
    params.require(:scrape_result).permit(:ruleset_id, :result_value)
  end

  def invalid_scrape_result
    redirect_to root_path, info: 'Invalid Scrape Result'
  end
end

app/controllers/scrapers_controller.rb
class ScrapersController < ApplicationController
  before_action :fetch_scraper, only: %i[edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_scraper

  def index
    @scrapers = Scraper.by_id
  end

  def new
    @scraper = Scraper.new
  end

  def create
    @scraper = Scraper.new(scraper_params)
    if @scraper.save
      flash[:success] = "Scraper #{@scraper.name} created successfully!"
      redirect_to scrapers_path
    else
      flash.now[:danger] = @scraper.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @scraper = Scraper.preload(rulesets: :scrape_results).find(params[:id])
  end

  def edit; end

  def update
    if @scraper.update(scraper_params)
      flash[:success] = "Scraper #{@scraper.name} updated successfully!"
      redirect_to scrapers_path
    else
      flash.now[:danger] = @scraper.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @scraper.destroy
    flash[:success] = 'Scraper deleted successfully'
    redirect_to root_path
  end

  private

  def scraper_params
    params.require(:scraper).permit(:name, :description)
  end

  def fetch_scraper
    @scraper = Scraper.find(params[:id])
  end

  def invalid_scraper
    redirect_to scrapers_path, info: 'Invalid Scraper'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rulesets_helper.rb
module RulesetsHelper
  def rule_xpath_icon(is_xpath)
    is_xpath ? asset_path('check_circle') : asset_path('x_circle')
  end
end

app/helpers/scrapers_helper.rb
module ScrapersHelper
  def last_scraped_value(ruleset)
    value = ruleset.scrape_results.last&.result_value
    value ? value : 'N/A'
  end

  def last_scraped_at(ruleset)
    scraped_at = ruleset.scrape_results.last&.created_at
    scraped_at ? scraped_at : 'N/A'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webscraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/layouts/flash_messages" %>
    <%= yield %>
  </body>
</html>

app/views/rulesets/edit.html.haml
.container
  .row
    %h1.w-100.text-center.mb-3 Edit Ruleset
  .row
    = render "shared/rulesets/form"

app/views/rulesets/new.html.haml
.container
  .row
    %h1.w-100.text-center.mb-3 New Ruleset
  .row
    = render "shared/rulesets/form"

app/views/rulesets/show.html.haml
.container
  .row
    %h1.w-100.text-center.mb-3= @ruleset.name
  .row.mb-3.justify-content-center
    .card.w-50
      %h5.card-header Details
      .card-body
        %h5.card-title
          Name:
          = @ruleset.name
        %p.card-text
          %div
            Description:
            = @ruleset.description
          %div
            URL:
            = link_to @ruleset.url, @ruleset.url, target: :blank
          %div
            Parent rule:
            %code= @ruleset.parent_rule
          %div
            Parent rule is XPath?:
            = image_tag(rule_xpath_icon(@ruleset.parent_rule_is_xpath?))
          - if @ruleset.has_child_rule?
            %div
              Child rule:
              %code= @ruleset.child_rule
            %div
              Parent rule is XPath?:
              = image_tag(rule_xpath_icon(@ruleset.child_rule_is_xpath?))
        .float-right
          = link_to "Edit Ruleset", edit_scraper_ruleset_path(@scraper, @ruleset), class: "btn btn-warning"
          = link_to "Delete Ruleset", scraper_ruleset_path(@scraper, @ruleset), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }
          = link_to "Back to Scraper", scraper_path(@scraper), class: "btn btn-dark"
          = link_to "Homepage", root_path, class: "btn btn-dark"
  .row
    .col-sm-12.pr-0.mb-1
      .float-right
        = link_to "Scrape now", scraper_ruleset_single_scrape_path(@scraper, @ruleset), class: "btn btn-primary"
  .row
    %h1.w-100.text-center.mb-1 Scrape results:
    %table.table
      %thead.thead-dark
        %tr
          %th{:scope => "col"} #
          %th{:scope => "col"} Value
          %th{:scope => "col"} Created at
          %th{:scope => "col"} Updated at
          %th{:scope => "col"} Actions
      %tbody
        - @ruleset.scrape_results.map.with_index do |scrape_result, index|
          %tr
            %th{:scope => "row"}= index + 1
            %td= scrape_result.result_value
            %td= scrape_result.created_at
            %td= scrape_result.updated_at
            %td
              = link_to "Show Scrape Result", scrape_result_path(scrape_result), class: "btn btn-info"
              = link_to "Delete Scrape Result", scrape_result_path(scrape_result), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }

app/views/scrape_results/edit.html.haml
.container
  .row
    %h1.w-100.text-center.mb-3 Edit Scrape Result
  .row
    = form_with model: @scrape_result, class: "form", local: true do |f|
      .form-group
        %label= f.label :result_value, "Result value:"
        = f.text_field :result_value, class: "form-control"
      = f.submit class: "btn btn-success"
      = link_to "Cancel", :back, class: "btn btn-danger"

app/views/scrape_results/show.html.haml
.container
  .row
    %h1.w-100.text-center.mb-3= @scrape_result.name
  .row.mb-3.justify-content-center
    .card
      %h5.card-header Details
      .card-body
        %h5.card-title
          Name:
          = @scrape_result.name
        %p.card-text
          %div
            Description:
            = @scrape_result.description
          %div
            Result value:
            %code= @scrape_result.result_value
          - if @scrape_result.manual_change?
            %div.bold
              Result was changed manually at:
              = @scrape_result.updated_at
        .float-right
          = link_to "Edit Scrape Result", edit_scrape_result_path(@scrape_result), class: "btn btn-warning"
          = link_to "Delete Scrape Result", scrape_result_path(@scrape_result), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }
          = link_to "Back to Ruleset", scraper_ruleset_path(@scrape_result.ruleset.scraper, @scrape_result.ruleset), class: "btn btn-dark"
          = link_to "Homepage", root_path, class: "btn btn-dark"

app/views/scrapers/edit.html.haml
.container
  .row
    %h1.w-100.text-center.mb-3 Edit Scraper
  .row
    = render "shared/scrapers/form"

app/views/scrapers/index.html.haml
.container
  .row
    %h1.w-100.text-center.mb-3 Your Scrapers
  .row
    .col-sm-12.pr-0.mb-1
      .float-right
        = link_to "New Scraper", new_scraper_path, class: "btn btn-primary"
  .row
    %table.table
      %thead.thead-dark
        %tr
          %th{:scope => "col"} #
          %th{:scope => "col"} Name
          %th{:scope => "col"} Description
          %th{:scope => "col"} Actions
      %tbody
        - @scrapers.map.with_index do |scraper, index|
          %tr
            %th{:scope => "row"}= index + 1
            %td= scraper.name
            %td= scraper.description
            %td
              = link_to "Show Scraper", scraper_path(scraper), class: "btn btn-info"
              = link_to "Edit Scraper", edit_scraper_path(scraper), class: "btn btn-warning"
              = link_to "Delete Scraper", scraper_path(scraper), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }

app/views/scrapers/new.html.haml
.container
  .row
    %h1.w-100.text-center.mb-3 New Scraper
  .row
    = render "shared/scrapers/form"

app/views/scrapers/show.html.haml
.container
  .row
    %h1.w-100.text-center.mb-3= @scraper.name
  .row.mb-3.justify-content-center
    .card.w-50
      %h5.card-header Details
      .card-body
        %h5.card-title
          Name:
          = @scraper.name
        %p.card-text
          Description:
          = @scraper.description
        .float-right
          = link_to "Edit Scraper", edit_scraper_path(@scraper), class: "btn btn-warning"
          = link_to "Delete Scraper", scraper_path(@scraper), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }
          = link_to "Homepage", root_path, class: "btn btn-dark"
  .row
    .col-sm-12.pr-0.mb-1
      .float-right
        = link_to "New Ruleset", new_scraper_ruleset_path(@scraper), class: "btn btn-primary"
  .row
    %h1.w-100.text-center.mb-1 Scraper rulesets:
    %table.table
      %thead.thead-dark
        %tr
          %th{:scope => "col"} #
          %th{:scope => "col"} Name
          %th{:scope => "col"} Description
          %th{:scope => "col"} Last scraped value
          %th{:scope => "col"} Last scraped at
          %th{:scope => "col"} Actions
      %tbody
        - @scraper.rulesets.map.with_index do |ruleset, index|
          %tr
            %th{:scope => "row"}= index + 1
            %td= ruleset.name
            %td= ruleset.description
            %td= last_scraped_value(ruleset)
            %td= last_scraped_at(ruleset)
            %td
              = link_to "Show Ruleset", scraper_ruleset_path(@scraper, ruleset), class: "btn btn-info"
              = link_to "Edit Ruleset", edit_scraper_ruleset_path(@scraper, ruleset), class: "btn btn-warning"
              = link_to "Delete Ruleset", scraper_ruleset_path(@scraper, ruleset), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }

app/views/shared/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/rulesets/_form.html.haml
= form_with model: @ruleset, url: scraper_rulesets_path, class: "form mb-3", local: true do |f|
  .form-group
    %label= f.label :name, "Ruleset name:"
    = f.text_field :name, class: "form-control"
  .form-group
    %label= f.label :description, "Ruleset description:"
    = f.text_area :description, class: "form-control", size: "60x12"
  .form-group
    %label= f.label :url, "URL:"
    = f.text_field :url, class: "form-control"
  .form-group
    = f.label :parent_rule_is_xpath, "Parent rule is XPath:"
    = f.check_box :parent_rule_is_xpath
  .form-group
    %label= f.label :parent_rule, "Parent rule:"
    = f.text_field :parent_rule, class: "form-control"
  .form-group
    = f.label :child_rule_is_xpath, "Child rule is XPath:"
    = f.check_box :child_rule_is_xpath
    %br
    %small This field is optional.
  .form-group
    %label= f.label :child_rule, "Child rule:"
    = f.text_field :child_rule, class: "form-control"
    %small This field is optional.
  = f.submit class: "btn btn-success"
  = link_to "Cancel", :back, class: "btn btn-danger"

app/views/shared/scrapers/_form.html.haml
= form_with model: @scraper, class: "form", local: true do |f|
  .form-group
    %label= f.label :name, 'Scraper name:'
    = f.text_field :name, class: "form-control"
  .form-group
    %label= f.label :description, "Scraper description:"
    = f.text_area :description, class: "form-control", size: "60x12"
  = f.submit class: "btn btn-success"
  = link_to "Cancel", :back, class: "btn btn-danger"